### ISSUE TITLE
Powiązanie między elementami przestrzennymi a planem

### ISSUE THREAD

**Issue by darekw** [recoded-co/zdecydujmy-razem#10]
Elementy przestrzenne zapisują się bez informacji o tym do jakiego planu są przypisane. Przy zapisywaniu polygony, markera, postu należy uzupełnić informacje o planie do jakiego należy poprzez relację Subject.

**Comment by MarcinRa** [comment]
Zweryfikowałem problem i w tej chwili dane dotyczące planu są przekazywane. Zamykam zadanie.
