### ISSUE TITLE
/dashboard nie reaguje na konfigurację

### ISSUE THREAD

**Issue by darekw** [recoded-co/zdecydujmy-razem#11]
~/dashboard nie reaguje na konfigurację. Zainstalowałem nową instancję, ustawiłem w panelu administratora nowy plan, dodałem nową konfigurację. Jest to jedyny plan i jedyna konfiguracja w bazie. Po wejściu na ~/dashboard pokazuje się inny fragment mapy i pasek z dyskusją po złej stronie.

**Comment by MarcinRa** [comment]
@darekw czy to zgłoszenie jest dalej aktualne?
