### ISSUE TITLE
Zmiana zakresu zoom przy zmianie mapy bazowej 

### ISSUE THREAD

**Issue by PMGIS** [recoded-co/zdecydujmy-razem#2]
- W momencie zmiany mapy bazowej zmienia się poziom zbliżenia. 
- W momencie wyboru Google Physical zmianie ulega również panel skali (staje się mniejszy).
- W momencie wyboru warstwy OSM panel wyboru warstwa zmienia swoją wielkość (czcionka i podkład).

**Comment by darekw** [comment]
Każda mapa udostępnia kilka poziomów zoom-u. Wskaźnik pokazuje aktualnie włączony zoom. Niestety różne mapy mają różną liczbę tych poziomów, prawdopodobnie z tego wynika dziwne zachowanie.
