### ISSUE TITLE
problem z logowaniem przez portale społecznościowe

### ISSUE THREAD

**Issue by darekw** [recoded-co/zdecydujmy-razem#3]
Po zalogowaniu do panelu administratora i przejściu na stronę główną nie następuje przekierowanie do dashboard, pojawia się ekran logowania. Przy próbie kliknięcia na "Konto Google" lub "Konto Facebook" leci wyjątek o tym, że konto jest w użyciu. Strona powinna rozpoznawać administratora jak normalnego użytkownika i przekierowywać do dashboard.

**Comment by MarcinRa** [comment]
Problem rozwiązany.
