### ISSUE TITLE
Błąd podczas logowania poprzez  konto gmaila 

### ISSUE THREAD

**Issue by PMGIS** [recoded-co/zdecydujmy-razem#5]
Kazia próbowała się zalogować poprzez gmaila i to się jej nie udaje. 
Przesyłam link i tekst z komunikatu jaki otrzymuje. 

http://www.zdecydujmyrazem.pl/social_auth/complete/google-oauth2/?state=x7YeUv5J3Skf53oUbFambxfCbGcrwFaf&code=4/wan8439MkUKVBF15s2FiLd0c7usS.UtfZsqySq7ESOl05ti8ZT3atubPPhAI

AuthCanceled at /social_auth/complete/google-oauth2/
Authentication process canceled
Request Method: GET
Request URL:    http://www.zdecydujmyrazem.pl/social_auth/complete/google-oauth2/?state=x7YeUv5J3Skf53oUbFambxfCbGcrwFaf&code=4/wan8439MkUKVBF15s2FiLd0c7usS.UtfZsqySq7ESOl05ti8ZT3atubPPhAI
Django Version: 1.5.4
Exception Type: AuthCanceled
Exception Value:  
Authentication process canceled
Exception Location: /home/projects/zdecydujmyrazem-github/zr-dep/lib/python2.7/site-packages/social_auth/backends/**init**.py in auth_complete, line 856
Python Executable:  /usr/bin/uwsgi-core
Python Version: 2.7.3
Python Path:  
['/home/projects/zdecydujmyrazem-github/zr-dep/lib/python2.7/site-packages',
 '/home/projects/zdecydujmyrazem-github/zdecydujmy-razem/',
 '.',
 '',
 '/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg',
 '/home/darek/miner/stratum-mining-proxy',
 '/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/autobahn-0.5.14-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pyOpenSSL-0.13-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/ecdsa-0.8-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/zope.interface-4.0.5-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/virtualenv-1.9.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pip-1.3.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/GDAL-1.10.0-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/Django-1.5.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/Genshi-0.7-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/Trac-1.0-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/geomet-0.1.0-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PIL']
Server time:    Nd, 17 List 2013 21:55:25 +0100

**Comment by MarcinRa** [comment]
Zgłoszenie zweryfikowane. Zamykam to zadanie.
