### ISSUE TITLE
Logowanie

### ISSUE THREAD

**Issue by PMGIS** [recoded-co/zdecydujmy-razem#6]
Zgodnie z komentarzem do zadnia "Wydanie nr 1. Rejestracja użytkownika" użytkownik powinien móc zalogować się do aplikacji podając labo login albo emaila. 
Obecnie nie da się zalogować używając emaila. 
Trzeba również poprawić opis przy panelu logowania na "Adres e-mail lub login"

**Comment by MarcinRa** [comment]
Problem rozwiązany
