### ISSUE TITLE
Przypominanie hasła 

### ISSUE THREAD

**Issue by PMGIS** [recoded-co/zdecydujmy-razem#7]
Podczas próby przypomnienia hasła otrzymałem komunikat:

SMTPServerDisconnected at /accounts/passreset/
please run connect() first
Request Method: POST
Request URL:    http://www.zdecydujmyrazem.pl/accounts/passreset/
Django Version: 1.5.4
Exception Type: SMTPServerDisconnected
Exception Value:  
please run connect() first
Exception Location: /usr/lib/python2.7/smtplib.py in send, line 326
Python Executable:  /usr/bin/uwsgi-core
Python Version: 2.7.3
Python Path:  
['/home/projects/zdecydujmyrazem-github/zr-dep/lib/python2.7/site-packages',
 '/home/projects/zdecydujmyrazem-github/zdecydujmy-razem/',
 '.',
 '',
 '/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg',
 '/home/darek/miner/stratum-mining-proxy',
 '/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/autobahn-0.5.14-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pyOpenSSL-0.13-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/ecdsa-0.8-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/zope.interface-4.0.5-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/virtualenv-1.9.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pip-1.3.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/GDAL-1.10.0-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/Django-1.5.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/Genshi-0.7-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/Trac-1.0-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/geomet-0.1.0-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PIL']
Server time:    Pon, 25 List 2013 23:42:20 +0100
Traceback Switch to copy-and-paste view

/home/projects/zdecydujmyrazem-github/zr-dep/lib/python2.7/site-packages/django/core/handlers/base.py in get_response
                        response = callback(request, _callback_args, *_callback_kwargs) ...
▶ Local vars
/home/projects/zdecydujmyrazem-github/zr-dep/lib/python2.7/site-packages/django/utils/decorators.py in _wrapped_view
                    response = view_func(request, _args, *_kwargs) ...
▶ Local vars
/home/projects/zdecydujmyrazem-github/zr-dep/lib/python2.7/site-packages/django/contrib/auth/views.py in password_reset
            form.save(**opts) ...
▶ Local vars
/home/projects/zdecydujmyrazem-github/zr-dep/lib/python2.7/site-packages/django/contrib/auth/forms.py in save
            send_mail(subject, email, from_email, [user.email]) ...
▶ Local vars
/home/projects/zdecydujmyrazem-github/zr-dep/lib/python2.7/site-packages/django/core/mail/__init__.py in send_mail
                        connection=connection).send() ...
▶ Local vars
/home/projects/zdecydujmyrazem-github/zr-dep/lib/python2.7/site-packages/django/core/mail/message.py in send
        return self.get_connection(fail_silently).send_messages([self]) ...
▶ Local vars
/home/projects/zdecydujmyrazem-github/zr-dep/lib/python2.7/site-packages/django/core/mail/backends/smtp.py in send_messages
            new_conn_created = self.open() ...
▶ Local vars
/home/projects/zdecydujmyrazem-github/zr-dep/lib/python2.7/site-packages/django/core/mail/backends/smtp.py in open
                self.connection.ehlo() ...
▶ Local vars
/usr/lib/python2.7/smtplib.py in ehlo
        self.putcmd(self.ehlo_msg, name or self.local_hostname) ...
▶ Local vars
/usr/lib/python2.7/smtplib.py in putcmd
        self.send(str) ...
▶ Local vars
/usr/lib/python2.7/smtplib.py in send
            raise SMTPServerDisconnected('please run connect() first') ...
▶ Local vars
Request information

GET
No GET data
POST
Variable    Value
csrfmiddlewaretoken 
u'TYuEkKypQVWOYZ4cfNRpYxc8b1Bb6c6k'
email  
u'mmlodk@amu.edu.pl'
FILES
No FILES data
COOKIES
Variable    Value
csrftoken  
'TYuEkKypQVWOYZ4cfNRpYxc8b1Bb6c6k'
sessionid  
'cfhnt4zgpumhargugm5npbfe8s8ecx2y'
META
Variable    Value
wsgi.multiprocess  
True
HTTP_REFERER  
'http://www.zdecydujmyrazem.pl/accounts/passreset/'
SCRIPT_NAME 
u''
REQUEST_METHOD  
'POST'
PATH_INFO  
u'/accounts/passreset/'
HTTP_ORIGIN 
'http://www.zdecydujmyrazem.pl'
SERVER_PROTOCOL 
'HTTP/1.1'
QUERY_STRING  
''
CONTENT_LENGTH  
'78'
HTTP_USER_AGENT 
'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.57 Safari/537.36'
HTTP_CONNECTION 
'keep-alive'
HTTP_COOKIE 
'sessionid=cfhnt4zgpumhargugm5npbfe8s8ecx2y; csrftoken=TYuEkKypQVWOYZ4cfNRpYxc8b1Bb6c6k'
SERVER_NAME 
'www.zdecydujmyrazem.pl'
REMOTE_ADDR 
'213.156.99.119'
wsgi.url_scheme 
'http'
SERVER_PORT 
'80'
uwsgi.node  
'Ubuntu-1204-precise-64-minimal'
DOCUMENT_ROOT  
'/etc/nginx/html'
HTTP_CONTENT_LENGTH 
'78'
wsgi.input  
<uwsgi._Input object at 0x2897a00>
HTTP_HOST  
'www.zdecydujmyrazem.pl'
wsgi.multithread  
False
HTTP_CACHE_CONTROL  
'max-age=0'
HTTP_CONTENT_TYPE  
'application/x-www-form-urlencoded'
REQUEST_URI 
'/accounts/passreset/'
HTTP_ACCEPT 
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8'
wsgi.version  
(1, 0)
wsgi.run_once  
False
wsgi.errors 
<open file 'wsgi_errors', mode 'w' at 0x7f0c4ae17030>
REMOTE_PORT 
'54678'
HTTP_ACCEPT_LANGUAGE  
'pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4'
uwsgi.version  
'1.0.3-debian'
CONTENT_TYPE  
'application/x-www-form-urlencoded'
wsgi.file_wrapper  
''
CSRF_COOKIE 
u'TYuEkKypQVWOYZ4cfNRpYxc8b1Bb6c6k'
HTTP_ACCEPT_ENCODING  
'gzip,deflate,sdch'
Settings
Using settings module zdecydujmyrazem.settings
Setting Value
USE_L10N  
True
USE_THOUSAND_SEPARATOR  
False
CSRF_COOKIE_SECURE  
False
LANGUAGE_CODE  
'pl'
ROOT_URLCONF  
'zdecydujmyrazem.urls'
MANAGERS  
()
TEMPLATE_LOADERS  
('django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader')
DEFAULT_CHARSET 
'utf-8'
SESSION_SERIALIZER  
'django.contrib.sessions.serializers.PickleSerializer'
STATIC_ROOT 
'/home/projects/zdecydujmyrazem-github/static/'
ALLOWED_HOSTS  
[]
MESSAGE_STORAGE 
'django.contrib.messages.storage.fallback.FallbackStorage'
EMAIL_SUBJECT_PREFIX  
'[Django] '
SEND_BROKEN_LINK_EMAILS 
False
STATICFILES_FINDERS 
('django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder')
NOTIFICATION_QUEUE_ALL  
True
GOOGLE_OAUTH2_CLIENT_ID 
'302320688030.apps.googleusercontent.com'
SESSION_CACHE_ALIAS 
'default'
SESSION_COOKIE_DOMAIN  
None
SESSION_COOKIE_NAME 
'sessionid'
ADMIN_FOR  
()
TIME_INPUT_FORMATS  
('%H:%M:%S', '%H:%M')
DATABASES  
{'default': {'ENGINE': 'django.contrib.gis.db.backends.postgis',
             'HOST': 'localhost',
             'NAME': 'm1-softgis',
             'OPTIONS': {},
             'PASSWORD': u'*******************_',
             'PORT': '5432',
             'TEST_CHARSET': None,
             'TEST_COLLATION': None,
             'TEST_MIRROR': None,
             'TEST_NAME': None,
             'TIME_ZONE': 'UTC',
             'USER': 'postgres'}}
FILE_UPLOAD_PERMISSIONS 
None
FILE_UPLOAD_HANDLERS  
('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')
DEFAULT_CONTENT_TYPE  
'text/html'
APPEND_SLASH  
True
FIRST_DAY_OF_WEEK  
0
DATABASE_ROUTERS  
[]
DEFAULT_TABLESPACE  
''
SOCIAL_AUTH_ASSOCIATION_HANDLE_LENGTH  
32
YEAR_MONTH_FORMAT  
'F Y'
STATICFILES_STORAGE 
'django.contrib.staticfiles.storage.StaticFilesStorage'
CACHES  
{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
SERVER_EMAIL  
'root@localhost'
SESSION_COOKIE_PATH 
'/'
MIDDLEWARE_CLASSES  
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')
USE_I18N  
True
THOUSAND_SEPARATOR  
','
SECRET_KEY  
u'**_****************_'
LANGUAGE_COOKIE_NAME  
'django_language'
FILE_UPLOAD_TEMP_DIR  
None
TRANSACTIONS_MANAGED  
False
LOGGING_CONFIG  
'django.utils.log.dictConfig'
SOCIAL_AUTH_ENABLED_BACKENDS  
('google', 'facebook')
GOOGLE_OAUTH2_CLIENT_SECRET 
u'**_****************_'
WSGI_APPLICATION  
'zdecydujmyrazem.wsgi.application'
TEMPLATE_DEBUG  
True
X_FRAME_OPTIONS 
'SAMEORIGIN'
AUTHENTICATION_BACKENDS 
('social_auth.backends.facebook.FacebookBackend',
 'social_auth.backends.google.GoogleOAuth2Backend',
 'django.contrib.auth.backends.ModelBackend')
FORCE_SCRIPT_NAME  
None
USE_X_FORWARDED_HOST  
False
SIGNING_BACKEND 
'django.core.signing.TimestampSigner'
SESSION_COOKIE_SECURE  
False
CSRF_COOKIE_DOMAIN  
None
FILE_CHARSET  
'utf-8'
DEBUG  
True
SESSION_FILE_PATH  
None
DEFAULT_FILE_STORAGE  
'django.core.files.storage.FileSystemStorage'
INSTALLED_APPS  
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'notification',
 'bootstrap_toolkit',
 'floppyforms',
 'rest_framework',
 'social_auth',
 'registration',
 'zr',
 'filemanager')
LANGUAGES  
(('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy-nl', 'Frisian'),
 ('ga', 'Irish'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('nb', 'Norwegian Bokmal'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-cn', 'Simplified Chinese'),
 ('zh-tw', 'Traditional Chinese'))
COMMENTS_ALLOW_PROFANITIES  
False
SOCIAL_AUTH_DEFAULT_USERNAME  
'new_social_auth_user'
STATICFILES_DIRS  
('/home/projects/zdecydujmyrazem-github/zr-dep/lib/python2.7/site-packages/rest_framework/templates',)
PREPEND_WWW 
False
SECURE_PROXY_SSL_HEADER 
None
SESSION_COOKIE_HTTPONLY 
True
FACEBOOK_APP_ID 
'623947990960027'
DEBUG_PROPAGATE_EXCEPTIONS  
False
MONTH_DAY_FORMAT  
'F j'
LOGIN_URL  
'/social_auth/login/'
SESSION_EXPIRE_AT_BROWSER_CLOSE 
False
SOCIAL_AUTH_ASSOCIATION_SERVER_URL_LENGTH  
32
TIME_FORMAT 
'P'
AUTH_USER_MODEL 
'auth.User'
DATE_INPUT_FORMATS  
('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')
LOGIN_ERROR_URL 
'/social_auth/login-error/'
CSRF_COOKIE_NAME  
'csrftoken'
EMAIL_HOST_PASSWORD 
u'**_****************_'
PASSWORD_RESET_TIMEOUT_DAYS 
u'**_****************_'
CACHE_MIDDLEWARE_ALIAS  
'default'
SESSION_SAVE_EVERY_REQUEST  
False
NUMBER_GROUPING 
0
SOCIAL_AUTH_NONCE_SERVER_URL_LENGTH 
32
SESSION_ENGINE  
'django.contrib.sessions.backends.db'
CSRF_FAILURE_VIEW  
'django.views.csrf.csrf_failure'
CSRF_COOKIE_PATH  
'/'
LOGIN_REDIRECT_URL  
'/zr/dashboard'
DECIMAL_SEPARATOR  
'.'
IGNORABLE_404_URLS  
()
LOCALE_PATHS  
()
TEMPLATE_STRING_IF_INVALID  
''
LOGOUT_URL  
'/accounts/logout/'
EMAIL_USE_TLS  
True
FIXTURE_DIRS  
()
EMAIL_HOST  
''
DATE_FORMAT 
'N j, Y'
FACEBOOK_API_SECRET 
u'**_****************_'
MEDIA_ROOT  
'/home/projects/zdecydujmyrazem-github/media/'
DEFAULT_EXCEPTION_REPORTER_FILTER  
'django.views.debug.SafeExceptionReporterFilter'
ADMINS  
()
FORMAT_MODULE_PATH  
None
DEFAULT_FROM_EMAIL  
'ZdecydujmyRazem notification@recoded.co'
REST_FRAMEWORK  
{'DEFAULT_FILTER_BACKENDS': ('rest_framework.filters.DjangoFilterBackend',),
 'DEFAULT_MODEL_SERIALIZER_CLASS': 'rest_framework.serializers.HyperlinkedModelSerializer',
 'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated']}
MEDIA_URL  
''
DATETIME_FORMAT 
'N j, Y, P'
TEMPLATE_DIRS  
()
SOCIAL_AUTH_UID_LENGTH  
32
SITE_ID 
1
DISALLOWED_USER_AGENTS  
()
ALLOWED_INCLUDE_ROOTS  
()
LOGGING 
{'disable_existing_loggers': False,
 'filters': {'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'}},
 'handlers': {'mail_admins': {'class': 'django.utils.log.AdminEmailHandler',
                              'filters': ['require_debug_false'],
                              'level': 'ERROR'}},
 'loggers': {'django.request': {'handlers': ['mail_admins'],
                                'level': 'ERROR',
                                'propagate': True}},
 'version': 1}
SHORT_DATE_FORMAT  
'm/d/Y'
TEST_RUNNER 
'django.test.simple.DjangoTestSuiteRunner'
CACHE_MIDDLEWARE_KEY_PREFIX 
u'**_****************_'
TIME_ZONE  
'Europe/Warsaw'
FILE_UPLOAD_MAX_MEMORY_SIZE 
2621440
EMAIL_BACKEND  
'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_SSL  
False
TEMPLATE_CONTEXT_PROCESSORS 
('django.contrib.auth.context_processors.auth',
 'social_auth.context_processors.social_auth_by_type_backends')
SESSION_COOKIE_AGE  
1209600
SETTINGS_MODULE 
'zdecydujmyrazem.settings'
USE_ETAGS  
False
LANGUAGES_BIDI  
('he', 'ar', 'fa')
DEFAULT_INDEX_TABLESPACE  
''
INTERNAL_IPS  
()
STATIC_URL  
'/static/'
EMAIL_PORT  
0
USE_TZ  
True
SHORT_DATETIME_FORMAT  
'm/d/Y P'
PASSWORD_HASHERS  
u'**_****************_'
ABSOLUTE_URL_OVERRIDES  
{}
CACHE_MIDDLEWARE_SECONDS  
600
DATETIME_INPUT_FORMATS  
('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')
EMAIL_HOST_USER 
''
PROFANITIES_LIST  
u'**_*****************'
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 500 page.

**Comment by MarcinRa** [comment]
Zadanie powielone. Zamykam
