### ISSUE TITLE
ZoomBar - znika 

### ISSUE THREAD

**Issue by PMGIS** [recoded-co/zdecydujmy-razem#9]
Przy dużej skali znika zoom bar. Jak oddalimy się tak na mapie przekrając mniej więcej połowę skali na zoom barze to on znika. Problem zauważyłem na przeglądarce chrome.

**Comment by MarcinRa** [comment]
Zweryfikowałem problem dla Chrome(Version 31.0.1650.63). Zamykam zadanie. Gdyby problem się powtórzył proszę o detale dotyczące rodzaju przeglądarki.
